from .Imagen4Custom import NODE_CLASS_MAPPINGS as _IMAGEN4_CLS, NODE_DISPLAY_NAME_MAPPINGS as _IMAGEN4_NAMES
from .Veo3Custom import NODE_CLASS_MAPPINGS as _VEO3_CLS, NODE_DISPLAY_NAME_MAPPINGS as _VEO3_NAMES
from .GeminiCustom import NODE_CLASS_MAPPINGS as _GEMINI_CLS, NODE_DISPLAY_NAME_MAPPINGS as _GEMINI_NAMES
from .VideoPreviewCustom import NODE_CLASS_MAPPINGS as _PREVIEW_CLS, NODE_DISPLAY_NAME_MAPPINGS as _PREVIEW_NAMES
from .Imagen3EditCustom import NODE_CLASS_MAPPINGS as _EDIT_CLS, NODE_DISPLAY_NAME_MAPPINGS as _EDIT_NAMES
from .UtilsCustom import NODE_CLASS_MAPPINGS as _UTILS_CLS, NODE_DISPLAY_NAME_MAPPINGS as _UTILS_NAMES

NODE_CLASS_MAPPINGS = {
    **_IMAGEN4_CLS, **_VEO3_CLS, **_GEMINI_CLS,
    **_PREVIEW_CLS, **_EDIT_CLS, **_UTILS_CLS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **_IMAGEN4_NAMES, **_VEO3_NAMES, **_GEMINI_NAMES,
    **_PREVIEW_NAMES, **_EDIT_NAMES, **_UTILS_NAMES,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
