from .Imagen4Custom import NODE_CLASS_MAPPINGS as _IMAGEN4_CLS, NODE_DISPLAY_NAME_MAPPINGS as _IMAGEN4_NAMES
from .Veo3Custom import NODE_CLASS_MAPPINGS as _VEO3_CLS, NODE_DISPLAY_NAME_MAPPINGS as _VEO3_NAMES
from .GeminiCustom import NODE_CLASS_MAPPINGS as _GEMINI_CLS, NODE_DISPLAY_NAME_MAPPINGS as _GEMINI_NAMES

NODE_CLASS_MAPPINGS = {**_IMAGEN4_CLS, **_VEO3_CLS, **_GEMINI_CLS}
NODE_DISPLAY_NAME_MAPPINGS = {**_IMAGEN4_NAMES, **_VEO3_NAMES, **_GEMINI_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
