from .gemini_vertex import NODE_CLASS_MAPPINGS as _IMG_CLS, NODE_DISPLAY_NAME_MAPPINGS as _IMG_NAMES
from .gemini_text import NODE_CLASS_MAPPINGS as _TXT_CLS, NODE_DISPLAY_NAME_MAPPINGS as _TXT_NAMES

NODE_CLASS_MAPPINGS = {**_IMG_CLS, **_TXT_CLS}
NODE_DISPLAY_NAME_MAPPINGS = {**_IMG_NAMES, **_TXT_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
